language: python
python:
    - "2.7"
    - "3.5"
    - "3.6"
    - "pypy"
    - "pypy3"
before_install:
    - sudo add-apt-repository -y ppa:mc3man/trusty-media
    - sudo apt-get update -qq
    - sudo apt-get install ffmpeg
install:
    - pip install coverage
script:
    - make test
    - make coverage
